library(stringr)
library(dplyr)
library(reshape2)
library(ggplot2)
library(viridis)
rm(list = ls())
aaincrease_minglc <- read.table(file = "AA_increase_min_glc.csv",
                                sep = ",",
                                header = TRUE)
colnames(aaincrease_minglc) = c('Benefits', 'Helps', 'Delta')
pp <-
  ggplot(aaincrease_minglc, aes(
    y = factor(Benefits),
    x = factor(Helps),
    fill = Delta
  )) +
  geom_point(aes(size = (Delta), colour = Delta),
             shape = 16,
             stroke = 0) +
  scale_color_gradient(low = 'lightblue', high = 'darkblue') +
  theme_bw() + theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title = element_text(size = 15),
    axis.text.y = element_text(
      vjust = 0.5,
      hjust = 1,
      face = 'italic',
      size = 10,
      color = 'black'
    ),
    axis.text.x = element_text(
      angle = 90,
      vjust = 0.5,
      hjust = 1,
      face = 'italic',
      size = 10,
      color = 'black'
    )
  ) +
  
  scale_y_discrete(
    breaks = c(
      'Acidaminococcus_fermentans_DSM_20731',
      'Akkermansia_muciniphila_ATCC_BAA_835',
      'Alistipes_finegoldii_DSM_17242',
      'Alistipes_putredinis_DSM_17216',
      'Alistipes_shahii_WAL_8301',
      'Bacteroides_caccae_ATCC_43185',
      'Bacteroides_coprocola_M16_DSM_17136',
      'Bacteroides_eggerthii_DSM_20697',
      'Bacteroides_fragilis_NCTC_9343',
      'Bacteroides_intestinalis_341_DSM_17393',
      'Bacteroides_stercoris_ATCC_43183',
      'Bacteroides_thetaiotaomicron_VPI_5482',
      'Bacteroides_uniformis_ATCC_8492',
      'Bifidobacterium_adolescentis_ATCC_15703',
      'Bifidobacterium_bifidum_PRL2010',
      'Bifidobacterium_longum_NCC2705',
      'Bilophila_wadsworthia_3_1_6',
      'Blautia_wexlerae_DSM_19850',
      'Citrobacter_amalonaticus_Y19',
      'Clostridium_clostridioforme_CM201',
      'Collinsella_tanakaei_YIT_12063',
      'Coprococcus_catus_GD_7',
      'Desulfovibrio_desulfuricans_subsp_desulfuricans_DSM_642',
      'Desulfovibrio_piger_ATCC_29098',
      'Dialister_invisus_DSM_15470',
      'Dorea_longicatena_DSM_13814',
      'Enterobacter_cloacae_EcWSU1',
      'Enterococcus_faecium_TX1330',
      'Escherichia_coli_str_K_12_substr_MG1655',
      'Eubacterium_rectale_M104_1',
      'Faecalibacterium_prausnitzii_L2_6',
      'Fusobacterium_nucleatum_subsp_nucleatum_ATCC_25586',
      'Fusobacterium_varium_ATCC_27725',
      'Haemophilus_parainfluenzae_T3T1',
      'Helicobacter_pylori_26695',
      'Klebsiella_pneumoniae_pneumoniae_MGH78578',
      'Lactobacillus_mucosae_LM1',
      'Lactobacillus_reuteri_SD2112_ATCC_55730',
      'Megasphaera_elsdenii_DSM_20460',
      'Parabacteroides_distasonis_ATCC_8503',
      'Parabacteroides_johnsonii_DSM_18315',
      'Phascolarctobacterium_succinatutens_YIT_12067',
      'Prevotella_ruminicola_23',
      'Pseudoflavonifractor_capillosus_strain_ATCC_29799',
      'Roseburia_intestinalis_L1_82',
      'Roseburia_inulinivorans_DSM_16841',
      'Ruminococcus_bromii_L2_63',
      'Ruminococcus_callidus_ATCC_2776001',
      'Ruminococcus_torques_ATCC_27756',
      'Shigella_flexneri_2002017',
      'Streptococcus_salivarius_JIM8777',
      'Subdoligranulum_variabile_DSM_15176',
      'Veillonella_atypica_ACS_049_V_Sch6'
    ),
    labels = c(
      'A. fermentans',
      'A. muciniphila',
      'A. finegoldii',
      'A. putredinis',
      'A. shahii',
      'B. caccae',
      'B. coprocola',
      'B. eggerthii',
      'B. fragilis',
      'B. intestinalis',
      'B. stercoris',
      'B. thetaiotaomicron',
      'B. uniformis',
      'B. adolescentis',
      'B. bifidum',
      'B. longum',
      'B. wadsworthia',
      'B. wexlerae',
      'C. amalonaticus',
      'C. clostridioforme',
      'C. tanakaei',
      'C. catus',
      'D. desulfuricans',
      'D. piger',
      'D. invisus',
      'D. longicatena',
      'E. cloacae',
      'E. faecium',
      'E. coli',
      'E. rectale',
      'F. prausnitzii',
      'F. nucleatum',
      'F. varium',
      'H. parainfluenzae',
      'H. pylori',
      'K. pneumoniae',
      'L. mucosae',
      'L. reuteri',
      'M. elsdenii',
      'P. distasonis',
      'P. johnsonii',
      'P. succinatutens',
      'P. ruminicola',
      'P. capillosus',
      'R. intestinalis',
      'R. inulinivorans',
      'R. bromii',
      'R. callidus',
      'R. torques',
      'S. flexneri',
      'S. salivarius',
      'S. variabile',
      'V. atypica'
    )
  ) +
  scale_x_discrete(
    breaks = c(
      'Acidaminococcus_fermentans_DSM_20731',
      'Akkermansia_muciniphila_ATCC_BAA_835',
      'Alistipes_finegoldii_DSM_17242',
      'Alistipes_putredinis_DSM_17216',
      'Alistipes_shahii_WAL_8301',
      'Bacteroides_caccae_ATCC_43185',
      'Bacteroides_coprocola_M16_DSM_17136',
      'Bacteroides_eggerthii_DSM_20697',
      'Bacteroides_fragilis_NCTC_9343',
      'Bacteroides_intestinalis_341_DSM_17393',
      'Bacteroides_stercoris_ATCC_43183',
      'Bacteroides_thetaiotaomicron_VPI_5482',
      'Bacteroides_uniformis_ATCC_8492',
      'Bifidobacterium_adolescentis_ATCC_15703',
      'Bifidobacterium_bifidum_PRL2010',
      'Bifidobacterium_longum_NCC2705',
      'Bilophila_wadsworthia_3_1_6',
      'Blautia_wexlerae_DSM_19850',
      'Citrobacter_amalonaticus_Y19',
      'Clostridium_clostridioforme_CM201',
      'Collinsella_tanakaei_YIT_12063',
      'Coprococcus_catus_GD_7',
      'Desulfovibrio_desulfuricans_subsp_desulfuricans_DSM_642',
      'Desulfovibrio_piger_ATCC_29098',
      'Dialister_invisus_DSM_15470',
      'Dorea_longicatena_DSM_13814',
      'Enterobacter_cloacae_EcWSU1',
      'Enterococcus_faecium_TX1330',
      'Escherichia_coli_str_K_12_substr_MG1655',
      'Eubacterium_rectale_M104_1',
      'Faecalibacterium_prausnitzii_L2_6',
      'Fusobacterium_nucleatum_subsp_nucleatum_ATCC_25586',
      'Fusobacterium_varium_ATCC_27725',
      'Haemophilus_parainfluenzae_T3T1',
      'Helicobacter_pylori_26695',
      'Klebsiella_pneumoniae_pneumoniae_MGH78578',
      'Lactobacillus_mucosae_LM1',
      'Lactobacillus_reuteri_SD2112_ATCC_55730',
      'Megasphaera_elsdenii_DSM_20460',
      'Parabacteroides_distasonis_ATCC_8503',
      'Parabacteroides_johnsonii_DSM_18315',
      'Phascolarctobacterium_succinatutens_YIT_12067',
      'Prevotella_ruminicola_23',
      'Pseudoflavonifractor_capillosus_strain_ATCC_29799',
      'Roseburia_intestinalis_L1_82',
      'Roseburia_inulinivorans_DSM_16841',
      'Ruminococcus_bromii_L2_63',
      'Ruminococcus_callidus_ATCC_2776001',
      'Ruminococcus_torques_ATCC_27756',
      'Shigella_flexneri_2002017',
      'Streptococcus_salivarius_JIM8777',
      'Subdoligranulum_variabile_DSM_15176',
      'Veillonella_atypica_ACS_049_V_Sch6'
    ),
    labels = c(
      'A. fermentans',
      'A. muciniphila',
      'A. finegoldii',
      'A. putredinis',
      'A. shahii',
      'B. caccae',
      'B. coprocola',
      'B. eggerthii',
      'B. fragilis',
      'B. intestinalis',
      'B. stercoris',
      'B. thetaiotaomicron',
      'B. uniformis',
      'B. adolescentis',
      'B. bifidum',
      'B. longum',
      'B. wadsworthia',
      'B. wexlerae',
      'C. amalonaticus',
      'C. clostridioforme',
      'C. tanakaei',
      'C. catus',
      'D. desulfuricans',
      'D. piger',
      'D. invisus',
      'D. longicatena',
      'E. cloacae',
      'E. faecium',
      'E. coli',
      'E. rectale',
      'F. prausnitzii',
      'F. nucleatum',
      'F. varium',
      'H. parainfluenzae',
      'H. pylori',
      'K. pneumoniae',
      'L. mucosae',
      'L. reuteri',
      'M. elsdenii',
      'P. distasonis',
      'P. johnsonii',
      'P. succinatutens',
      'P. ruminicola',
      'P. capillosus',
      'R. intestinalis',
      'R. inulinivorans',
      'R. bromii',
      'R. callidus',
      'R. torques',
      'S. flexneri',
      'S. salivarius',
      'S. variabile',
      'V. atypica'
    )
  ) +
  xlab('Helps') + ylab('Benefits') +
  labs(colour = "Increase in number of amino acids") +
  guides(
    colour = guide_legend("Increase in number of AA"),
    fill = guide_legend("Increase in number of AA"),
    size = guide_legend("Increase in number of AA")
  )

print(pp)
